// src/app/layout.js

import { ChakraProvider } from "@chakra-ui/react";

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My Next.js App with Chakra UI</title>
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ChakraProvider>
          {/* Main content of the app */}
          <main>{children}</main>
        </ChakraProvider>
      </body>
    </html>
  );
}
