// src/app/layout.js
"use client";

import { ChakraProvider } from "@chakra-ui/react";
import theme from "./theme";

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My Next.js App with Chakra UI</title>
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.ico" />
        {/* Google Fonts embed code */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ChakraProvider theme={theme}>
          <main>{children}</main>
        </ChakraProvider>
      </body>
    </html>
  );
}
